[package]
name = "script-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# hashbrown = "0.9"
serde = { version = "1", features = ["derive"] }
